version: 0.2

phases:
      
  pre_build:
    commands:
      - echo Pre Build started on `date`

  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`

